### ISSUE TITLE
Integrate dbt with BigQuery

### ISSUE THREAD

**Issue by owseaman** [toursbylocals/wiki#118]
Description:

dbt is a transformational modeling tool that enables data analysts and engineers to more easily build and manage data pipelines. 

This issue is to integrate dbt with BigQuery, to allow dbt to deploy models to BigQuery and utilize BigQuery as the warehouse for dbt operations.

## Tasks:

- [ ] Research dbt BigQuery integration 

- [ ] Add BigQuery profile configuration to dbt project

- [ ] Configure dbt to use service account for BQ access

- [ ] Test connectivity and initial model deployment

- [ ] Document process for BigQuery dbt integration

- [ ] Build example dbt models to deploy to BQ 

- [ ] Run tests to validate model builds in BQ

- [ ] Add Warehouse YAML configuration for BigQuery 

- [ ] Update README on setting up dbt with BQ

## Dependencies:

- dbt installed and configured with profiles.yml
- BigQuery project and dataset created
- BigQuery service account JSON key downloaded
