### ISSUE TITLE
Guide Account | Settings | Personal Information | Payout Method (Adyen Countries)

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#160]
## SUMMARY
Within the `Kitchen`, we have a section called `Personal Information` where the Guides can input all the individual information, the payout details and KYC to Adyen, if needed. Overall, the section contains:
- KYC link for onboarding, if Adyen Country
- Payout options if non-Adyen Country (Direct deposit, PayPal or Wire Transfer)
- Depending on the payout selected, the fields required are different

Note: 
This ticket is for Adyen Guides. We don't need to ask for bank details as all that is being done directly on Adyen KYC

### ACS

- [ ] Create the page following the design on `Figma`
- [ ] Input data would be individual/organization, name, country & currency
- [ ] Generate the unique link for the Guide following https://github.com/toursbylocals/tblv3/issues/1037 (same implementation but with v3 branding)
- [ ] Redirect guides to Ayden's KYC process following https://github.com/toursbylocals/tblv3/issues/1037 (same implementation but with v3 branding)
- [ ] Show a message page when guides complete the KYC process on Adyen's end following https://github.com/toursbylocals/tblv3/issues/1037 (same implementation but with v3 branding)
- [ ] All fields are mandatory
- [ ] Generate the link and add changeLegalEntityType=true param with the link. (request from Naoki)

### VISUALS
**Initial page**
<img width="1368" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3M1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9429979148e92dc67c3f8b3fd589655c232c41e8/Screenshot%202023-12-06%20at%2010.02.46.png" alt="Screenshot 2023-12-06 at 10.02.46.png" />

**Organizations**
<img width="1366" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0U2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--54f90ac1d1581a5d3eff6ef1509fcfd5d0328f39/Screenshot%202023-12-06%20at%2010.03.10.png" alt="Screenshot 2023-12-06 at 10.03.10.png" />

**Return page**
<img width="1364" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1U2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dd4288ae4ea8517ec6aa7e392080baff327fdd25/Screenshot%202023-12-06%20at%2010.03.52.png" alt="Screenshot 2023-12-06 at 10.03.52.png" />

### RESOURCES
[Figma Link to Personal Information](https://www.figma.com/file/05Lni9rdCbn4jzXrvnaYPe/Kitchen?type=design&node-id=11088-123820&mode=design&t=Y78CMqrW6dBX9tLS-0)
[Figma Link to Prototype](https://www.figma.com/proto/05Lni9rdCbn4jzXrvnaYPe/Kitchen?page-id=11088%3A123820&type=design&node-id=11088-125031&t=Y78CMqrW6dBX9tLS-0&scaling=scale-down&starting-point-node-id=11088%3A123865&show-proto-sidebar=1)

**Comment by YumiKimbara** [comment]
@kateinvan @sebas-led @laskokonopa @ecurtosi99 @Mica-pfl
Can you check the URL below when you have time?

After you have visited onboarding link at lease once, you will skip the first page and redirect onboardning link automatically.

https://tblv3-kitchen-staging-c94ff87374cd.herokuapp.com/guide/settings

[ykimbara@toursbylocals.com](mailto:ykimbara@toursbylocals.com)
Cupcake1234!

**Comment by sebas-led** [comment]
@YumiKimbara 
- Once user is redirected to Adyen, there is no option to go back on the screen. Could you check? If not possible to add a 'Go back', then we could probably open in a new tab?
- After saving changes and going back to KITCHEN, the payout method shows PayPal while it should display Direct Deposit for every Adyen guide. Could you take a look?

<img width="1384" alt="Screenshot 2024-02-22 at 14 08 08" src="https://github.com/toursbylocals/wiki/assets/107880609/337e9cbd-87ed-4572-ae3b-0ac56cf53f15">

**Comment by YumiKimbara** [comment]
@kateinvan I found the same issue. It was working fine when I merged... I will investigate the issue today, and let you know here once it has been fixed!

**Comment by YumiKimbara** [comment]
@kateinvan @sebas-led 

Naoki and I figured out that the issue is coming from Adyen. It is their internal error, so there is nothing I can do until they fix this issue. Please give me a few days, and I will try to keep checking if the issue has been fixed or not before working on my fix related to QA.

**Comment by YumiKimbara** [comment]
@kateinvan Adyen issue seems have been fixed. Could you review it when you have time?

**Comment by kateinvan** [comment]
@YumiKimbaraI I first saw a back button on the Adyen page, but it was gone on my second attempt.

**Comment by sebas-led** [comment]
@YumiKimbara Overall, looks good ! I have only one situation with my test guide that would like to double check with you:
- Guide id 65aee3bab883ddd442039980 is in an Adyen country and has finished the KYC at Adyen. However, all the information under Personal Information and the Payment Method are showing as empty on Kitchen. Could you check?
- Same Guide, but when I try to add any information under Personal Information, as soon as I type the first letter, I get redirected to the Onboarding link at Adyen or get an Application error. How could a guide update their personal information in this case?

https://github.com/toursbylocals/wiki/assets/107880609/72a59659-25e0-4756-859a-ec780624dabb

**Comment by YumiKimbara** [comment]
@sebas-led Thank you! I will investigate this issue. Also, button on the adyen link is still not appearing, so I will move this ticket back to in ToDo

**Comment by YumiKimbara** [comment]
@kateinvan @sebas-led @laskokonopa @ecurtosi99 @Mica-pfl
Can you check the URL below when you have time?

https://tblv3-kitchen-staging-c94ff87374cd.herokuapp.com/guide/settings

>Once user is redirected to Adyen, there is no option to go back on the screen. Could you check? If not possible to add a 'Go back', then we could probably open in a new tab?

This is fixed!

>Guide id 65aee3bab883ddd442039980 is in an Adyen country and has finished the KYC at Adyen. However, all the information under Personal Information and the Payment Method are showing as empty on Kitchen. Could you check?

As I talked with Seba on DM a few days ago, this is fixed.

>Same Guide, but when I try to add any information under Personal Information, as soon as I type the first letter, I get redirected to the Onboarding link at Adyen or get an Application error. How could a guide update their personal information in this case?

As I talked with Seba on DM a few days ago, this is fixed.

[ykimbara@toursbylocals.com](mailto:ykimbara@toursbylocals.com)
Cupcake1234!

**Comment by kateinvan** [comment]
LGTM

**Comment by ecurtosi99** [comment]
LGTM

**Comment by laskokonopa** [comment]
LGTM

**Comment by sebas-led** [comment]
LGTM
